import { Answer } from "./answer";
import { Console } from "./answer";

const cupPathPrefix = "/assets/Cups";
const consolePathPrefix = "/assets/ConsoleOrigins";

export const answerSet: Array<Answer> = [
  {
    trackName: "Mario Kart Stadium",
    song: "https://www.mariowiki.com/images/7/7a/MK8-Music-MarioKartStadium.oga?d1f20",
    trackLayoutPath: `${cupPathPrefix}/Mushroom/MarioKartStadium/map.png`,
    cup: "Mushroom Cup",
    screenshotPath: `${cupPathPrefix}/Mushroom/MarioKartStadium/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Mushroom/MarioKartStadium/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Mushroom/MushroomCup.png`,
    consoleOrigin: Console.WiiU,
    consolePath: `${consolePathPrefix}/WiiU.png`,
  },
  {
    trackName: "Water Park",
    song: "https://www.mariowiki.com/images/a/a1/MK8-Music-WaterPark.oga?b805f",
    trackLayoutPath: `${cupPathPrefix}/Mushroom/WaterPark/map.png`,
    cup: "Mushroom Cup",
    screenshotPath: `${cupPathPrefix}/Mushroom/WaterPark/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Mushroom/WaterPark/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Mushroom/MushroomCup.png`,
    consoleOrigin: Console.WiiU,
    consolePath: `${consolePathPrefix}/WiiU.png`,
  },
  {
    trackName: "Sweet Sweet Canyon",
    song: "https://www.mariowiki.com/images/7/79/MK8-Music-SweetSweetCanyon.oga?d3314",
    trackLayoutPath: `${cupPathPrefix}/Mushroom/SweetSweetCanyon/map.png`,
    cup: "Mushroom Cup",
    screenshotPath: `${cupPathPrefix}/Mushroom/SweetSweetCanyon/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Mushroom/SweetSweetCanyon/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Mushroom/MushroomCup.png`,
    consoleOrigin: Console.WiiU,
    consolePath: `${consolePathPrefix}/WiiU.png`,
  },
  {
    trackName: "Thwomp Ruins",
    song: "https://www.mariowiki.com/images/7/75/MK8-Music-ThwompRuins.oga?6c787",
    trackLayoutPath: `${cupPathPrefix}/Mushroom/ThwompRuins/map.png`,
    cup: "Mushroom Cup",
    screenshotPath: `${cupPathPrefix}/Mushroom/ThwompRuins/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Mushroom/ThwompRuins/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Mushroom/MushroomCup.png`,
    consoleOrigin: Console.WiiU,
    consolePath: `${consolePathPrefix}/WiiU.png`,
  },
  {
    trackName: "Mario Circuit (Wii U)",
    song: "https://www.mariowiki.com/images/0/09/MK8-Music-MarioCircuit.oga?2a3f4",
    trackLayoutPath: `${cupPathPrefix}/Flower/MarioCircuit/map.png`,
    cup: "Flower Cup",
    screenshotPath: `${cupPathPrefix}/Flower/MarioCircuit/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Flower/MarioCircuit/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Flower/FlowerCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Toad Harbor",
    song: "https://www.mariowiki.com/images/6/6b/MK8-Music-ToadHarbor.oga?7484d",
    trackLayoutPath: `${cupPathPrefix}/Flower/ToadHarbor/map.png`,
    cup: "Flower Cup",
    screenshotPath: `${cupPathPrefix}/Flower/ToadHarbor/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Flower/ToadHarbor/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Flower/FlowerCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Twisted Mansion",
    song: "https://www.mariowiki.com/images/6/6f/MK8-Music-TwistedMansion.oga?0e841",
    trackLayoutPath: `${cupPathPrefix}/Flower/TwistedMansion/map.png`,
    cup: "Flower Cup",
    screenshotPath: `${cupPathPrefix}/Flower/TwistedMansion/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Flower/TwistedMansion/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Flower/FlowerCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Shy Guy Falls",
    song: "https://www.mariowiki.com/images/6/63/MK8-Music-ShyGuyFalls.oga?4951c",
    trackLayoutPath: `${cupPathPrefix}/Flower/ShyGuyFalls/map.png`,
    cup: "Flower Cup",
    screenshotPath: `${cupPathPrefix}/Flower/ShyGuyFalls/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Flower/ShyGuyFalls/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Flower/FlowerCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Sunshine Airport",
    song: "https://www.mariowiki.com/images/4/4c/MK8-Music-SunshineAirport.oga?a6dbf",
    trackLayoutPath: `${cupPathPrefix}/Star/SunshineAirport/map.png`,
    cup: "Star Cup",
    screenshotPath: `${cupPathPrefix}/Star/SunshineAirport/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Star/SunshineAirport/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Star/StarCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Dolphin Shoals",
    song: "https://www.mariowiki.com/images/8/8c/MK8-Music-DolphinShoals.oga?2fcea",
    trackLayoutPath: `${cupPathPrefix}/Star/DolphinShoals/map.png`,
    cup: "Star Cup",
    screenshotPath: `${cupPathPrefix}/Star/DolphinShoals/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Star/DolphinShoals/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Star/StarCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Electrodrome",
    song: "https://www.mariowiki.com/images/1/1e/MK8-Music-Electrodrome.oga?a7de7",
    trackLayoutPath: `${cupPathPrefix}/Star/Electrodrome/map.png`,
    cup: "Star Cup",
    screenshotPath: `${cupPathPrefix}/Star/Electrodrome/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Star/Electrodrome/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Star/StarCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Mount Wario",
    song: "https://www.mariowiki.com/images/1/1c/MK8-Music-MountWario.oga?4e3c5",
    trackLayoutPath: `${cupPathPrefix}/Star/MountWario/map.png`,
    cup: "Star Cup",
    screenshotPath: `${cupPathPrefix}/Star/MountWario/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Star/MountWario/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Star/StarCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Cloudtop Cruise",
    song: "https://www.mariowiki.com/images/c/c0/MK8-Music-CloudtopCruise.oga?9fdab",
    trackLayoutPath: `${cupPathPrefix}/Star/CloudtopCruise/map.png`,
    cup: "Star Cup",
    screenshotPath: `${cupPathPrefix}/Star/CloudtopCruise/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Star/CloudtopCruise/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Star/StarCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Bone-Dry Dunes",
    song: "https://www.mariowiki.com/images/3/3f/MK8-Music-BoneDryDunes.oga?b09d4",
    trackLayoutPath: `${cupPathPrefix}/Special/BoneDryDunes/map.png`,
    cup: "Special Cup",
    screenshotPath: `${cupPathPrefix}/Special/BoneDryDunes/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Special/BoneDryDunes/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Special/SpecialCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Bowser's Castle",
    song: "https://www.mariowiki.com/images/9/90/MK8-Music-BowsersCastle.oga?cddd5",
    trackLayoutPath: `${cupPathPrefix}/Special/BowsersCastle/map.png`,
    cup: "Special Cup",
    screenshotPath: `${cupPathPrefix}/Special/BowsersCastle/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Special/BowsersCastle/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Special/SpecialCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Rainbow Road (Wii U)",
    song: "https://www.mariowiki.com/images/c/cf/MK8-Music-RainbowRoad.oga?217c4",
    trackLayoutPath: `${cupPathPrefix}/Special/RainbowRoad/map.png`,
    cup: "Special Cup",
    screenshotPath: `${cupPathPrefix}/Special/RainbowRoad/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Special/RainbowRoad/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Special/SpecialCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Moo Moo Meadows",
    song: "https://www.mariowiki.com/images/e/ee/MK8-Music-Wii-MooMooMeadows.oga?10b60",
    trackLayoutPath: `${cupPathPrefix}/Shell/MooMooMeadows/map.png`,
    cup: "Shell Cup",
    screenshotPath: `${cupPathPrefix}/Shell/MooMooMeadows/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Shell/MooMooMeadows/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Shell/ShellCup.png`,
    consolePath: `${consolePathPrefix}/Wii.png`,
    consoleOrigin: Console.Wii,
  },
  {
    trackName: "Mario Circuit (GBA)",
    song: "https://www.mariowiki.com/images/1/10/MK8-Music-GBA-MarioCircuit.oga?30753",
    trackLayoutPath: `${cupPathPrefix}/Shell/MarioCircuitGBA/map.png`,
    cup: "Shell Cup",
    screenshotPath: `${cupPathPrefix}/Shell/MarioCircuitGBA/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Shell/MarioCircuitGBA/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Shell/ShellCup.png`,
    consolePath: `${consolePathPrefix}/GBA.png`,
    consoleOrigin: Console.GBA,
  },
  {
    trackName: "Cheep Cheep Beach",
    song: "https://www.mariowiki.com/images/e/e0/MK8-Music-DS-CheepCheepBeach.oga?c89ad",
    trackLayoutPath: `${cupPathPrefix}/Shell/CheepCheepBeach/map.png`,
    cup: "Shell Cup",
    screenshotPath: `${cupPathPrefix}/Shell/CheepCheepBeach/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Shell/CheepCheepBeach/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Shell/ShellCup.png`,
    consolePath: `${consolePathPrefix}/DS.png`,
    consoleOrigin: Console.DS,
  },
  {
    trackName: "Toad's Turnpike",
    song: "https://www.mariowiki.com/images/6/69/MK8-Music-N64-ToadsTurnpike.oga?b134f",
    trackLayoutPath: `${cupPathPrefix}/Shell/ToadsTurnpike/map.png`,
    cup: "Shell Cup",
    screenshotPath: `${cupPathPrefix}/Shell/ToadsTurnpike/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Shell/ToadsTurnpike/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Shell/ShellCup.png`,
    consolePath: `${consolePathPrefix}/N64.png`,
    consoleOrigin: Console.N64,
  },
  {
    trackName: "Dry Dry Desert",
    song: "https://www.mariowiki.com/images/e/e7/MK8-Music-GCN-DryDryDesert.oga?3cc03",
    trackLayoutPath: `${cupPathPrefix}/Banana/DryDryDesert/map.png`,
    cup: "Banana Cup",
    screenshotPath: `${cupPathPrefix}/Banana/DryDryDesert/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Banana/DryDryDesert/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Banana/BananaCup.png`,
    consolePath: `${consolePathPrefix}/GameCube.png`,
    consoleOrigin: Console.GameCube,
  },
  {
    trackName: "Donut Plains 3",
    song: "https://www.mariowiki.com/images/8/8e/MK8-Music-SNES-DonutPlains3.oga?193dd",
    trackLayoutPath: `${cupPathPrefix}/Banana/DonutPlains3/map.png`,
    cup: "Banana Cup",
    screenshotPath: `${cupPathPrefix}/Banana/DonutPlains3/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Banana/DonutPlains3/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Banana/BananaCup.png`,
    consolePath: `${consolePathPrefix}/SNES.png`,
    consoleOrigin: Console.SNES,
  },
  {
    trackName: "Royal Raceway",
    song: "https://www.mariowiki.com/images/7/7b/MK8-Music-N64-RoyalRaceway.oga?77543",
    trackLayoutPath: `${cupPathPrefix}/Banana/RoyalRaceway/map.png`,
    cup: "Banana Cup",
    screenshotPath: `${cupPathPrefix}/Banana/RoyalRaceway/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Banana/RoyalRaceway/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Banana/BananaCup.png`,
    consolePath: `${consolePathPrefix}/N64.png`,
    consoleOrigin: Console.N64,
  },
  {
    trackName: "DK Jungle",
    song: "https://www.mariowiki.com/images/7/7a/MK8-Music-3DS-DKJungle.oga?37ee2",
    trackLayoutPath: `${cupPathPrefix}/Banana/DKJungle/map.png`,
    cup: "Banana Cup",
    screenshotPath: `${cupPathPrefix}/Banana/DKJungle/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Banana/DKJungle/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Banana/BananaCup.png`,
    consolePath: `${consolePathPrefix}/N3DS.png`,
    consoleOrigin: Console.N3DS,
  },
  {
    trackName: "Wario Stadium",
    song: "https://www.mariowiki.com/images/2/2e/MK8-Music-DS-WarioStadium.oga?b6e7d",
    trackLayoutPath: `${cupPathPrefix}/Leaf/WarioStadium/map.png`,
    cup: "Leaf Cup",
    screenshotPath: `${cupPathPrefix}/Leaf/WarioStadium/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Leaf/WarioStadium/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Leaf/LeafCup.png`,
    consolePath: `${consolePathPrefix}/DS.png`,
    consoleOrigin: Console.DS,
  },
  {
    trackName: "Sherbet Land",
    song: "https://www.mariowiki.com/images/5/5b/MK8-Music-GCN-SherbetLand.oga?62915",
    trackLayoutPath: `${cupPathPrefix}/Leaf/SherbetLand/map.png`,
    cup: "Leaf Cup",
    screenshotPath: `${cupPathPrefix}/Leaf/SherbetLand/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Leaf/SherbetLand/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Leaf/LeafCup.png`,
    consolePath: `${consolePathPrefix}/GameCube.png`,
    consoleOrigin: Console.GameCube,
  },
  {
    trackName: "Music Park",
    song: "https://www.mariowiki.com/images/9/94/MK8-Music-3DS-MusicPark.oga?afc3b",
    trackLayoutPath: `${cupPathPrefix}/Leaf/MusicPark/map.png`,
    cup: "Leaf Cup",
    screenshotPath: `${cupPathPrefix}/Leaf/MusicPark/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Leaf/MusicPark/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Leaf/LeafCup.png`,
    consolePath: `${consolePathPrefix}/N3DS.png`,
    consoleOrigin: Console.N3DS,
  },
  {
    trackName: "Yoshi Valley",
    song: "https://www.mariowiki.com/images/e/e9/MK8-Music-N64-YoshiValley.oga?0c7f5",
    trackLayoutPath: `${cupPathPrefix}/Leaf/YoshiValley/map.png`,
    cup: "Leaf Cup",
    screenshotPath: `${cupPathPrefix}/Leaf/YoshiValley/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Leaf/YoshiValley/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Leaf/LeafCup.png`,
    consolePath: `${consolePathPrefix}/N64.png`,
    consoleOrigin: Console.N64,
  },
  {
    trackName: "Tick-Tock Clock",
    song: "https://www.mariowiki.com/images/8/84/MK8-Music-DS-TickTockClock.oga?56ac9",
    trackLayoutPath: `${cupPathPrefix}/Lightning/TickTockClock/map.png`,
    cup: "Lightning Cup",
    screenshotPath: `${cupPathPrefix}/Lightning/TickTockClock/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Lightning/TickTockClock/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Lightning/LightningCup.png`,
    consolePath: `${consolePathPrefix}/DS.png`,
    consoleOrigin: Console.DS,
  },
  {
    trackName: "Piranha Plant Slide",
    song: "https://www.mariowiki.com/images/c/ca/MK8-Music-3DS-PiranhaPlantSlide.oga?6b3e3",
    trackLayoutPath: `${cupPathPrefix}/Lightning/PiranhaPlantSlide/map.png`,
    cup: "Lightning Cup",
    screenshotPath: `${cupPathPrefix}/Lightning/PiranhaPlantSlide/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Lightning/PiranhaPlantSlide/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Lightning/LightningCup.png`,
    consolePath: `${consolePathPrefix}/N3DS.png`,
    consoleOrigin: Console.N3DS,
  },
  {
    trackName: "Grumble Volcano",
    song: "https://www.mariowiki.com/images/7/74/MK8-Music-Wii-GrumbleVolcano.oga?c6065",
    trackLayoutPath: `${cupPathPrefix}/Lightning/GrumbleVolcano/map.png`,
    cup: "Lightning Cup",
    screenshotPath: `${cupPathPrefix}/Lightning/GrumbleVolcano/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Lightning/GrumbleVolcano/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Lightning/LightningCup.png`,
    consolePath: `${consolePathPrefix}/Wii.png`,
    consoleOrigin: Console.Wii,
  },
  {
    trackName: "Rainbow Road (N64)",
    song: "https://www.mariowiki.com/images/0/09/MK8-Music-N64-RainbowRoad.oga?6b45d",
    trackLayoutPath: `${cupPathPrefix}/Lightning/RainbowRoadN64/map.png`,
    cup: "Lightning Cup",
    screenshotPath: `${cupPathPrefix}/Lightning/RainbowRoadN64/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Lightning/RainbowRoadN64/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Lightning/LightningCup.png`,
    consolePath: `${consolePathPrefix}/N64.png`,
    consoleOrigin: Console.N64,
  },
  {
    trackName: "Yoshi Circuit",
    song: "https://www.mariowiki.com/images/e/ec/MK8-DLC-Music-GCN-YoshiCircuit.oga?59949",
    trackLayoutPath: `${cupPathPrefix}/Egg/YoshiCircuit/map.png`,
    cup: "Egg Cup",
    screenshotPath: `${cupPathPrefix}/Egg/YoshiCircuit/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Egg/YoshiCircuit/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Egg/EggCup.png`,
    consolePath: `${consolePathPrefix}/GameCube.png`,
    consoleOrigin: Console.GameCube,
  },
  {
    trackName: "Excitebike Arena",
    song: "https://www.mariowiki.com/images/6/64/MK8-DLC-Music-ExcitebikeArena.oga?0c056",
    trackLayoutPath: `${cupPathPrefix}/Egg/ExcitebikeArena/map.png`,
    cup: "Egg Cup",
    screenshotPath: `${cupPathPrefix}/Egg/ExcitebikeArena/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Egg/ExcitebikeArena/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Egg/EggCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Dragon Driftway",
    song: "https://www.mariowiki.com/images/4/43/MK8-DLC-Music-DragonDriftway.oga?af28c",
    trackLayoutPath: `${cupPathPrefix}/Egg/DragonDriftway/map.png`,
    cup: "Egg Cup",
    screenshotPath: `${cupPathPrefix}/Egg/DragonDriftway/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Egg/DragonDriftway/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Egg/EggCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Mute City",
    song: "https://www.mariowiki.com/images/7/70/MK8-DLC-Music-MuteCity.oga?ed268",
    trackLayoutPath: `${cupPathPrefix}/Egg/MuteCity/map.png`,
    cup: "Egg Cup",
    screenshotPath: `${cupPathPrefix}/Egg/MuteCity/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Egg/MuteCity/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Egg/EggCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Wario's Gold Mine",
    song: "https://www.mariowiki.com/images/1/1c/MK8-DLC-Music-Wii-WariosGoldMine.oga?06faf",
    trackLayoutPath: `${cupPathPrefix}/Triforce/WariosGoldMine/map.png`,
    cup: "Triforce Cup",
    screenshotPath: `${cupPathPrefix}/Triforce/WariosGoldMine/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Triforce/WariosGoldMine/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Triforce/TriforceCup.png`,
    consolePath: `${consolePathPrefix}/Wii.png`,
    consoleOrigin: Console.Wii,
  },
  {
    trackName: "Rainbow Road (SNES)",
    song: "https://www.mariowiki.com/images/1/1b/MK8-DLC-Music-SNES-RainbowRoad.oga?ae831",
    trackLayoutPath: `${cupPathPrefix}/Triforce/RainbowRoadSNES/map.png`,
    cup: "Triforce Cup",
    screenshotPath: `${cupPathPrefix}/Triforce/RainbowRoadSNES/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Triforce/RainbowRoadSNES/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Triforce/TriforceCup.png`,
    consolePath: `${consolePathPrefix}/SNES.png`,
    consoleOrigin: Console.SNES,
  },
  {
    trackName: "Ice Ice Outpost",
    song: "https://www.mariowiki.com/images/1/1c/MK8-DLC-Music-IceIceOutpost.oga?0da36",
    trackLayoutPath: `${cupPathPrefix}/Triforce/IceIceOutpost/map.png`,
    cup: "Triforce Cup",
    screenshotPath: `${cupPathPrefix}/Triforce/IceIceOutpost/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Triforce/IceIceOutpost/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Triforce/TriforceCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Hyrule Circuit",
    song: "https://www.mariowiki.com/images/c/ca/MK8-DLC-Music-HyruleCircuit.oga?4439a",
    trackLayoutPath: `${cupPathPrefix}/Triforce/HyruleCircuit/map.png`,
    cup: "Triforce Cup",
    screenshotPath: `${cupPathPrefix}/Triforce/HyruleCircuit/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Triforce/HyruleCircuit/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Triforce/TriforceCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Baby Park",
    song: "https://www.mariowiki.com/images/b/b7/MK8-DLC-Music-GCN-BabyPark.oga?f6fb5",
    trackLayoutPath: `${cupPathPrefix}/Crossing/BabyPark/map.png`,
    cup: "Crossing Cup",
    screenshotPath: `${cupPathPrefix}/Crossing/BabyPark/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Crossing/BabyPark/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Crossing/CrossingCup.png`,
    consolePath: `${consolePathPrefix}/GameCube.png`,
    consoleOrigin: Console.GameCube,
  },
  {
    trackName: "Cheese Land",
    song: "https://www.mariowiki.com/images/3/3b/MK8-DLC-Music-GBA-CheeseLand.oga?78ed5",
    trackLayoutPath: `${cupPathPrefix}/Crossing/CheeseLand/map.png`,
    cup: "Crossing Cup",
    screenshotPath: `${cupPathPrefix}/Crossing/CheeseLand/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Crossing/CheeseLand/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Crossing/CrossingCup.png`,
    consolePath: `${consolePathPrefix}/GBA.png`,
    consoleOrigin: Console.GBA,
  },
  {
    trackName: "Wild Woods",
    song: "https://www.mariowiki.com/images/0/0a/MK8-DLC-Music-WildWoods.oga?69b08",
    trackLayoutPath: `${cupPathPrefix}/Crossing/WildWoods/map.png`,
    cup: "Crossing Cup",
    screenshotPath: `${cupPathPrefix}/Crossing/WildWoods/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Crossing/WildWoods/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Crossing/CrossingCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Animal Crossing",
    song: "https://www.mariowiki.com/images/e/e9/MK8-DLC-Music-AnimalCrossingSpring.oga?d26d0",
    trackLayoutPath: `${cupPathPrefix}/Crossing/AnimalCrossing/map.png`,
    cup: "Crossing Cup",
    screenshotPath: `${cupPathPrefix}/Crossing/AnimalCrossing/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Crossing/AnimalCrossing/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Crossing/CrossingCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Neo Bowser City",
    song: "https://www.mariowiki.com/images/a/ae/MK8-DLC-Music-3DS-NeoBowserCity.oga?c9e23",
    trackLayoutPath: `${cupPathPrefix}/Bell/NeoBowserCity/map.png`,
    cup: "Bell Cup",
    screenshotPath: `${cupPathPrefix}/Bell/NeoBowserCity/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Bell/NeoBowserCity/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Bell/BellCup.png`,
    consolePath: `${consolePathPrefix}/N3DS.png`,
    consoleOrigin: Console.N3DS,
  },
  {
    trackName: "Ribbon Road",
    song: "https://www.mariowiki.com/images/1/1e/MK8-DLC-Music-GBA-RibbonRoad.oga?4ac4a",
    trackLayoutPath: `${cupPathPrefix}/Bell/RibbonRoad/map.png`,
    cup: "Bell Cup",
    screenshotPath: `${cupPathPrefix}/Bell/RibbonRoad/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Bell/RibbonRoad/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Bell/BellCup.png`,
    consolePath: `${consolePathPrefix}/GBA.png`,
    consoleOrigin: Console.GBA,
  },
  {
    trackName: "Super Bell Subway",
    song: "https://www.mariowiki.com/images/a/ab/MK8-DLC-Music-SuperBellSubway.oga?78b52",
    trackLayoutPath: `${cupPathPrefix}/Bell/SuperBellSubway/map.png`,
    cup: "Bell Cup",
    screenshotPath: `${cupPathPrefix}/Bell/SuperBellSubway/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Bell/SuperBellSubway/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Bell/BellCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Big Blue",
    song: "https://www.mariowiki.com/images/8/85/MK8-DLC-Music-BigBlue.oga?7ace4",
    trackLayoutPath: `${cupPathPrefix}/Bell/BigBlue/map.png`,
    cup: "Bell Cup",
    screenshotPath: `${cupPathPrefix}/Bell/BigBlue/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Bell/BigBlue/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Bell/BellCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Paris Promenade",
    song: "https://www.mariowiki.com/images/4/4b/TourParisPromenade_MK8DXBCP.oga?5b031",
    trackLayoutPath: `${cupPathPrefix}/GoldenDash/ParisPromenade/map.png`,
    cup: "Golden Dash Cup",
    screenshotPath: `${cupPathPrefix}/GoldenDash/ParisPromenade/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/GoldenDash/ParisPromenade/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/GoldenDash/GoldenDashCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Toad Circuit",
    song: "https://www.mariowiki.com/images/0/0f/3DSToadCircuit_MK8DXBCP.oga?9ca7c",
    trackLayoutPath: `${cupPathPrefix}/GoldenDash/ToadCircuit/map.png`,
    cup: "Golden Dash Cup",
    screenshotPath: `${cupPathPrefix}/GoldenDash/ToadCircuit/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/GoldenDash/ToadCircuit/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/GoldenDash/GoldenDashCup.png`,
    consolePath: `${consolePathPrefix}/N3DS.png`,
    consoleOrigin: Console.N3DS,
  },
  {
    trackName: "Choco Mountain",
    song: "https://www.mariowiki.com/images/0/0c/N64ChocoMountain_MK8DXBCP.oga?5313d",
    trackLayoutPath: `${cupPathPrefix}/GoldenDash/ChocoMountain/map.png`,
    cup: "Golden Dash Cup",
    screenshotPath: `${cupPathPrefix}/GoldenDash/ChocoMountain/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/GoldenDash/ChocoMountain/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/GoldenDash/GoldenDashCup.png`,
    consolePath: `${consolePathPrefix}/N64.png`,
    consoleOrigin: Console.N64,
  },
  {
    trackName: "Coconut Mall",
    song: "https://www.mariowiki.com/images/d/da/CoconutMallMK8DX.oga?db4aa",
    trackLayoutPath: `${cupPathPrefix}/GoldenDash/CoconutMall/map.png`,
    cup: "Golden Dash Cup",
    screenshotPath: `${cupPathPrefix}/GoldenDash/CoconutMall/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/GoldenDash/CoconutMall/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/GoldenDash/GoldenDashCup.png`,
    consolePath: `${consolePathPrefix}/Wii.png`,
    consoleOrigin: Console.Wii,
  },
  {
    trackName: "Tokyo Blur",
    song: "https://www.mariowiki.com/images/c/cd/TourTokyoBlur_MK8DXBCP.oga?974dc",
    trackLayoutPath: `${cupPathPrefix}/LuckyCat/TokyoBlur/map.png`,
    cup: "Lucky Cat Cup",
    screenshotPath: `${cupPathPrefix}/LuckyCat/TokyoBlur/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/LuckyCat/TokyoBlur/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/LuckyCat/LuckyCatCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Shroom Ridge",
    song: "https://www.mariowiki.com/images/a/af/DSShroomRidge_MK8DXBCP.oga?a0999",
    trackLayoutPath: `${cupPathPrefix}/LuckyCat/ShroomRidge/map.png`,
    cup: "Lucky Cat Cup",
    screenshotPath: `${cupPathPrefix}/LuckyCat/ShroomRidge/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/LuckyCat/ShroomRidge/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/LuckyCat/LuckyCatCup.png`,
    consolePath: `${consolePathPrefix}/DS.png`,
    consoleOrigin: Console.DS,
  },
  {
    trackName: "Sky Garden",
    song: "https://www.mariowiki.com/images/2/2c/GBASkyGarden_MK8DXBCP.oga?407ef",
    trackLayoutPath: `${cupPathPrefix}/LuckyCat/SkyGarden/map.png`,
    cup: "Lucky Cat Cup",
    screenshotPath: `${cupPathPrefix}/LuckyCat/SkyGarden/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/LuckyCat/SkyGarden/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/LuckyCat/LuckyCatCup.png`,
    consolePath: `${consolePathPrefix}/GBA.png`,
    consoleOrigin: Console.GBA,
  },
  {
    trackName: "Ninja Hideaway",
    song: "https://www.mariowiki.com/images/7/75/TourNinjaHideaway_MK8DXBCP.oga?433d0",
    trackLayoutPath: `${cupPathPrefix}/LuckyCat/NinjaHideaway/map.png`,
    cup: "Lucky Cat Cup",
    screenshotPath: `${cupPathPrefix}/LuckyCat/NinjaHideaway/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/LuckyCat/NinjaHideaway/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/LuckyCat/LuckyCatCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "New York Minute",
    song: "https://www.mariowiki.com/images/a/ab/Switch_Tour_NewYorkMinute_BCP.oga?63c2c",
    trackLayoutPath: `${cupPathPrefix}/Turnip/NewYorkMinute/map.png`,
    cup: "Turnip Cup",
    screenshotPath: `${cupPathPrefix}/Turnip/NewYorkMinute/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Turnip/NewYorkMinute/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Turnip/TurnipCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Mario Circuit 3",
    song: "https://www.mariowiki.com/images/5/58/Switch_SNES_MarioCircuit3_BCP.oga?9935e",
    trackLayoutPath: `${cupPathPrefix}/Turnip/MarioCircuit3/map.png`,
    cup: "Turnip Cup",
    screenshotPath: `${cupPathPrefix}/Turnip/MarioCircuit3/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Turnip/MarioCircuit3/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Turnip/TurnipCup.png`,
    consolePath: `${consolePathPrefix}/SNES.png`,
    consoleOrigin: Console.SNES,
  },
  {
    trackName: "Kalimari Desert",
    song: "https://www.mariowiki.com/images/0/0a/Switch_N64_KalimariDesert_BCP.oga?0f319",
    trackLayoutPath: `${cupPathPrefix}/Turnip/KalimariDesert/map.png`,
    cup: "Turnip Cup",
    screenshotPath: `${cupPathPrefix}/Turnip/KalimariDesert/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Turnip/KalimariDesert/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Turnip/TurnipCup.png`,
    consolePath: `${consolePathPrefix}/N64.png`,
    consoleOrigin: Console.N64,
  },
  {
    trackName: "Waluigi Pinball",
    song: "https://www.mariowiki.com/images/0/0e/MK8DX-CourseIntro_WaluigiPinball.oga?779a4",
    trackLayoutPath: `${cupPathPrefix}/Turnip/WaluigiPinball/map.png`,
    cup: "Turnip Cup",
    screenshotPath: `${cupPathPrefix}/Turnip/WaluigiPinball/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Turnip/WaluigiPinball/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Turnip/TurnipCup.png`,
    consolePath: `${consolePathPrefix}/DS.png`,
    consoleOrigin: Console.DS,
  },
  {
    trackName: "Sydney Sprint",
    song: "https://www.mariowiki.com/images/6/6f/Switch_Tour_SydneySprint_BCP.oga?8c7cb",
    trackLayoutPath: `${cupPathPrefix}/Propeller/SydneySprint/map.png`,
    cup: "Propeller Cup",
    screenshotPath: `${cupPathPrefix}/Propeller/SydneySprint/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Propeller/SydneySprint/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Propeller/PropellerCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Snow Land",
    song: "https://www.mariowiki.com/images/c/cd/Switch_GBA_SnowLand_BCP.oga?4e6f0",
    trackLayoutPath: `${cupPathPrefix}/Propeller/SnowLand/map.png`,
    cup: "Propeller Cup",
    screenshotPath: `${cupPathPrefix}/Propeller/SnowLand/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Propeller/SnowLand/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Propeller/PropellerCup.png`,
    consolePath: `${consolePathPrefix}/GBA.png`,
    consoleOrigin: Console.GBA,
  },
  {
    trackName: "Mushroom Gorge",
    song: "https://www.mariowiki.com/images/5/52/Switch_Wii_MushroomGorge_BCP.oga?7c3ce",
    trackLayoutPath: `${cupPathPrefix}/Propeller/MushroomGorge/map.png`,
    cup: "Propeller Cup",
    screenshotPath: `${cupPathPrefix}/Propeller/MushroomGorge/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Propeller/MushroomGorge/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Propeller/PropellerCup.png`,
    consolePath: `${consolePathPrefix}/Wii.png`,
    consoleOrigin: Console.Wii,
  },
  {
    trackName: "Sky-High Sundae",
    song: "https://www.mariowiki.com/images/3/36/Switch_Sky-HighSundae_BCP.oga?7bd9e",
    trackLayoutPath: `${cupPathPrefix}/Propeller/SkyHighSundae/map.png`,
    cup: "Propeller Cup",
    screenshotPath: `${cupPathPrefix}/Propeller/SkyHighSundae/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Propeller/SkyHighSundae/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Propeller/PropellerCup.png`,
    consolePath: `${consolePathPrefix}/Switch.png`,
    consoleOrigin: Console.Switch,
  },
  {
    trackName: "London Loop",
    song: "https://www.mariowiki.com/images/c/c7/Switch_Tour_LondonLoop_BCP.oga?e7f08",
    trackLayoutPath: `${cupPathPrefix}/Rock/LondonLoop/map.png`,
    cup: "Rock Cup",
    screenshotPath: `${cupPathPrefix}/Rock/LondonLoop/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Rock/LondonLoop/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Rock/RockCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Boo Lake",
    song: "https://www.mariowiki.com/images/e/ef/Switch_GBA_BooLake_BCP.oga?85ca9",
    trackLayoutPath: `${cupPathPrefix}/Rock/BooLake/map.png`,
    cup: "Rock Cup",
    screenshotPath: `${cupPathPrefix}/Rock/BooLake/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Rock/BooLake/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Rock/RockCup.png`,
    consolePath: `${consolePathPrefix}/GBA.png`,
    consoleOrigin: Console.GBA,
  },
  {
    trackName: "Rock Rock Mountain",
    song: "https://www.mariowiki.com/images/5/52/Switch_3DS_AlpinePass_BCP.oga?4e73e",
    trackLayoutPath: `${cupPathPrefix}/Rock/RockRockMountain/map.png`,
    cup: "Rock Cup",
    screenshotPath: `${cupPathPrefix}/Rock/RockRockMountain/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Rock/RockRockMountain/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Rock/RockCup.png`,
    consolePath: `${consolePathPrefix}/N3DS.png`,
    consoleOrigin: Console.N3DS,
  },
  {
    trackName: "Maple Treeway",
    song: "https://www.mariowiki.com/images/6/62/Switch_Wii_MapleTreeway_BCP.oga?11cac",
    trackLayoutPath: `${cupPathPrefix}/Rock/MapleTreeway/map.png`,
    cup: "Rock Cup",
    screenshotPath: `${cupPathPrefix}/Rock/MapleTreeway/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Rock/MapleTreeway/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Rock/RockCup.png`,
    consolePath: `${consolePathPrefix}/Wii.png`,
    consoleOrigin: Console.Wii,
  },
  {
    trackName: "Berlin Byways",
    song: "https://www.mariowiki.com/images/9/95/Switch_Tour_BerlinByways_BCP.oga?f245b",
    trackLayoutPath: `${cupPathPrefix}/Moon/BerlinByways/map.png`,
    cup: "Moon Cup",
    screenshotPath: `${cupPathPrefix}/Moon/BerlinByways/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Moon/BerlinByways/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Moon/MoonCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Peach Gardens",
    song: "https://www.mariowiki.com/images/9/95/Switch_Tour_BerlinByways_BCP.oga?f245b",
    trackLayoutPath: `${cupPathPrefix}/Moon/PeachGardens/map.png`,
    cup: "Moon Cup",
    screenshotPath: `${cupPathPrefix}/Moon/PeachGardens/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Moon/PeachGardens/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Moon/MoonCup.png`,
    consolePath: `${consolePathPrefix}/DS.png`,
    consoleOrigin: Console.DS,
  },
  {
    trackName: "Merry Mountain",
    song: "https://www.mariowiki.com/images/1/1d/TourMerryMountain_MK8DXBCP.oga?784a2",
    trackLayoutPath: `${cupPathPrefix}/Moon/MerryMountain/map.png`,
    cup: "Moon Cup",
    screenshotPath: `${cupPathPrefix}/Moon/MerryMountain/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Moon/MerryMountain/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Moon/MoonCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Rainbow Road (3DS)",
    song: "https://www.mariowiki.com/images/b/bd/Switch_3DS_RainbowRoad_BCP.oga?a2d67",
    trackLayoutPath: `${cupPathPrefix}/Moon/RainbowRoad3DS/map.png`,
    cup: "Moon Cup",
    screenshotPath: `${cupPathPrefix}/Moon/RainbowRoad3DS/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Moon/RainbowRoad3DS/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Moon/MoonCup.png`,
    consolePath: `${consolePathPrefix}/N3DS.png`,
    consoleOrigin: Console.N3DS,
  },
  {
    trackName: "Amsterdam Drift",
    song: "https://www.mariowiki.com/images/6/65/Switch_Tour_AmsterdamDrift_BCP.oga?16cbc",
    trackLayoutPath: `${cupPathPrefix}/Fruit/AmsterdamDrift/map.png`,
    cup: "Fruit Cup",
    screenshotPath: `${cupPathPrefix}/Fruit/AmsterdamDrift/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Fruit/AmsterdamDrift/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Fruit/FruitCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Riverside Park",
    song: "https://www.mariowiki.com/images/a/a9/Switch_GBA_RiversidePark_BCP.oga?32b71",
    trackLayoutPath: `${cupPathPrefix}/Fruit/RiversidePark/map.png`,
    cup: "Fruit Cup",
    screenshotPath: `${cupPathPrefix}/Fruit/RiversidePark/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Fruit/RiversidePark/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Fruit/FruitCup.png`,
    consolePath: `${consolePathPrefix}/GBA.png`,
    consoleOrigin: Console.GBA,
  },
  {
    trackName: "DK Summit",
    song: "https://www.mariowiki.com/images/5/5d/Switch_Wii_DKSummit_BCP.oga?70dce",
    trackLayoutPath: `${cupPathPrefix}/Fruit/DKSummit/map.png`,
    cup: "Fruit Cup",
    screenshotPath: `${cupPathPrefix}/Fruit/DKSummit/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Fruit/DKSummit/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Fruit/FruitCup.png`,
    consolePath: `${consolePathPrefix}/Wii.png`,
    consoleOrigin: Console.Wii,
  },
  {
    trackName: "Yoshi's Island",
    song: "https://www.mariowiki.com/images/0/03/Switch_Yoshi%27sIsland_BCP.oga?34ac9",
    trackLayoutPath: `${cupPathPrefix}/Fruit/YoshisIsland/map.png`,
    cup: "Fruit Cup",
    screenshotPath: `${cupPathPrefix}/Fruit/YoshisIsland/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Fruit/YoshisIsland/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Fruit/FruitCup.png`,
    consolePath: `${consolePathPrefix}/Switch.png`,
    consoleOrigin: Console.Switch,
  },
  {
    trackName: "Bangkok Rush",
    song: "https://www.mariowiki.com/images/2/29/Switch_Tour_BangkokRush_BCP.oga?193d9",
    trackLayoutPath: `${cupPathPrefix}/Boomerang/BangkokRush/map.png`,
    cup: "Boomerang Cup",
    screenshotPath: `${cupPathPrefix}/Boomerang/BangkokRush/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Boomerang/BangkokRush/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Boomerang/BoomerangCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Mario Circuit (DS)",
    song: "https://www.mariowiki.com/images/d/d6/Switch_DS_MarioCircuit_BCP.oga?bdc2b",
    trackLayoutPath: `${cupPathPrefix}/Boomerang/MarioCircuitDS/map.png`,
    cup: "Boomerang Cup",
    screenshotPath: `${cupPathPrefix}/Boomerang/MarioCircuitDS/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Boomerang/MarioCircuitDS/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Boomerang/BoomerangCup.png`,
    consolePath: `${consolePathPrefix}/DS.png`,
    consoleOrigin: Console.DS,
  },
  {
    trackName: "Waluigi Stadium",
    song: "https://www.mariowiki.com/images/c/cf/Switch_GCN_WaluigiStadium_BCP.oga?8b254",
    trackLayoutPath: `${cupPathPrefix}/Boomerang/WaluigiStadium/map.png`,
    cup: "Boomerang Cup",
    screenshotPath: `${cupPathPrefix}/Boomerang/WaluigiStadium/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Boomerang/WaluigiStadium/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Boomerang/BoomerangCup.png`,
    consolePath: `${consolePathPrefix}/GameCube.png`,
    consoleOrigin: Console.GameCube,
  },
  {
    trackName: "Singapore Speedway",
    song: "https://www.mariowiki.com/images/c/c6/Switch_Tour_SingaporeSpeedway_BCP.oga?e511e",
    trackLayoutPath: `${cupPathPrefix}/Boomerang/SingaporeSpeedway/map.png`,
    cup: "Boomerang Cup",
    screenshotPath: `${cupPathPrefix}/Boomerang/SingaporeSpeedway/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Boomerang/SingaporeSpeedway/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Boomerang/BoomerangCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Athens Dash",
    song: "https://www.mariowiki.com/images/8/85/Switch_Tour_AthensDash_BCP.oga?4c759",
    trackLayoutPath: `${cupPathPrefix}/Feather/AthensDash/map.png`,
    cup: "Feather Cup",
    screenshotPath: `${cupPathPrefix}/Feather/AthensDash/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Feather/AthensDash/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Feather/FeatherCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Daisy Cruiser",
    song: "https://www.mariowiki.com/images/1/15/Switch_GCN_DaisyCruiser_BCP.oga?cd508",
    trackLayoutPath: `${cupPathPrefix}/Feather/DaisyCruiser/map.png`,
    cup: "Feather Cup",
    screenshotPath: `${cupPathPrefix}/Feather/DaisyCruiser/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Feather/DaisyCruiser/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Feather/FeatherCup.png`,
    consolePath: `${consolePathPrefix}/GameCube.png`,
    consoleOrigin: Console.GameCube,
  },
  {
    trackName: "Moonview Highway",
    song: "https://www.mariowiki.com/images/a/a1/Switch_Wii_MoonviewHighway_BCP.oga?82f6f",
    trackLayoutPath: `${cupPathPrefix}/Feather/MoonviewHighway/map.png`,
    cup: "Feather Cup",
    screenshotPath: `${cupPathPrefix}/Feather/MoonviewHighway/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Feather/MoonviewHighway/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Feather/FeatherCup.png`,
    consolePath: `${consolePathPrefix}/Wii.png`,
    consoleOrigin: Console.Wii,
  },
  {
    trackName: "Squeaky Clean Sprint",
    song: "https://www.mariowiki.com/images/c/cc/Switch_SqueakyCleanSprint_BCP.oga?6fa56",
    trackLayoutPath: `${cupPathPrefix}/Feather/SqueakyCleanSprint/map.png`,
    cup: "Feather Cup",
    screenshotPath: `${cupPathPrefix}/Feather/SqueakyCleanSprint/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Feather/SqueakyCleanSprint/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Feather/FeatherCup.png`,
    consolePath: `${consolePathPrefix}/Switch.png`,
    consoleOrigin: Console.Switch,
  },
  {
    trackName: "Los Angeles Laps",
    song: "https://www.mariowiki.com/images/2/21/Switch_Tour_LosAngelesLaps_BCP.oga?0a1c0",
    trackLayoutPath: `${cupPathPrefix}/Cherry/LosAngelesLaps/map.png`,
    cup: "Cherry Cup",
    screenshotPath: `${cupPathPrefix}/Cherry/LosAngelesLaps/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Cherry/LosAngelesLaps/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Cherry/CherryCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Sunset Wilds",
    song: "https://www.mariowiki.com/images/9/91/Switch_GBA_SunsetWilds_BCP.oga?39353",
    trackLayoutPath: `${cupPathPrefix}/Cherry/SunsetWilds/map.png`,
    cup: "Cherry Cup",
    screenshotPath: `${cupPathPrefix}/Cherry/SunsetWilds/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Cherry/SunsetWilds/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Cherry/CherryCup.png`,
    consolePath: `${consolePathPrefix}/GBA.png`,
    consoleOrigin: Console.GBA,
  },
  {
    trackName: "Koopa Cape",
    song: "https://www.mariowiki.com/images/9/96/Switch_Wii_KoopaCape_BCP.oga?b4442",
    trackLayoutPath: `${cupPathPrefix}/Cherry/KoopaCape/map.png`,
    cup: "Cherry Cup",
    screenshotPath: `${cupPathPrefix}/Cherry/KoopaCape/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Cherry/KoopaCape/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Cherry/CherryCup.png`,
    consolePath: `${consolePathPrefix}/Wii.png`,
    consoleOrigin: Console.Wii,
  },
  {
    trackName: "Vancouver Velocity",
    song: "https://www.mariowiki.com/images/a/a0/Switch_Tour_VancouverVelocity_BCP.oga?d4cdd",
    trackLayoutPath: `${cupPathPrefix}/Cherry/VancouverVelocity/map.png`,
    cup: "Cherry Cup",
    screenshotPath: `${cupPathPrefix}/Cherry/VancouverVelocity/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Cherry/VancouverVelocity/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Cherry/CherryCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Rome Avanati",
    song: "https://www.mariowiki.com/images/e/e6/Switch_Tour_Rome_Avanti_BCP.oga?7ec46",
    trackLayoutPath: `${cupPathPrefix}/Acorn/RomeAvanti/map.png`,
    cup: "Acorn Cup",
    screenshotPath: `${cupPathPrefix}/Acorn/RomeAvanti/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Acorn/RomeAvanti/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Acorn/AcornCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "DK Mountain",
    song: "https://www.mariowiki.com/images/6/6a/Switch_GCN_DK_Mountain_BCP.oga?41146",
    trackLayoutPath: `${cupPathPrefix}/Acorn/DKMountain/map.png`,
    cup: "Acorn Cup",
    screenshotPath: `${cupPathPrefix}/Acorn/DKMountain/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Acorn/DKMountain/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Acorn/AcornCup.png`,
    consolePath: `${consolePathPrefix}/GameCube.png`,
    consoleOrigin: Console.GameCube,
  },
  {
    trackName: "Daisy Circuit",
    song: "https://www.mariowiki.com/images/b/b6/Switch_Wii_DaisyCircuit_BCP.mp3?702ce",
    trackLayoutPath: `${cupPathPrefix}/Acorn/DaisyCircuit/map.png`,
    cup: "Acorn Cup",
    screenshotPath: `${cupPathPrefix}/Acorn/DaisyCircuit/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Acorn/DaisyCircuit/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Acorn/AcornCup.png`,
    consolePath: `${consolePathPrefix}/Wii.png`,
    consoleOrigin: Console.Wii,
  },
  {
    trackName: "Piranha Plant Cove",
    song: "https://www.mariowiki.com/images/e/eb/Switch_Tour_Piranha_Plant_Cove_BCP.oga?4279f",
    trackLayoutPath: `${cupPathPrefix}/Acorn/PiranhaPlantCove/map.png`,
    cup: "Acorn Cup",
    screenshotPath: `${cupPathPrefix}/Acorn/PiranhaPlantCove/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Acorn/PiranhaPlantCove/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Acorn/AcornCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Madrid Drive",
    song: "https://www.mariowiki.com/images/3/36/Switch_Tour_MadridDrive_BCP.mp3?7570a",
    trackLayoutPath: `${cupPathPrefix}/Spiny/MadridDrive/map.png`,
    cup: "Spiny Cup",
    screenshotPath: `${cupPathPrefix}/Spiny/MadridDrive/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Spiny/MadridDrive/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Spiny/SpinyCup.png`,
    consolePath: `${consolePathPrefix}/Tour.png`,
    consoleOrigin: Console.Tour,
  },
  {
    trackName: "Rosalina's Ice World",
    song: "https://www.mariowiki.com/images/a/ab/Switch_3DS_Rosalina%27s_Ice_World_BCP.oga?5a678",
    trackLayoutPath: `${cupPathPrefix}/Spiny/RosalinasIceWorld/map.png`,
    cup: "Spiny Cup",
    screenshotPath: `${cupPathPrefix}/Spiny/RosalinasIceWorld/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Spiny/RosalinasIceWorld/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Spiny/SpinyCup.png`,
    consolePath: `${consolePathPrefix}/N3DS.png`,
    consoleOrigin: Console.N3DS,
  },
  {
    trackName: "Bowser Castle 3",
    song: "https://www.mariowiki.com/images/9/98/Switch_SNES_Bowser_Castle_3_BCP.oga?e9b84",
    trackLayoutPath: `${cupPathPrefix}/Spiny/BowserCastle3/map.png`,
    cup: "Spiny Cup",
    screenshotPath: `${cupPathPrefix}/Spiny/BowserCastle3/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Spiny/BowserCastle3/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Spiny/SpinyCup.png`,
    consolePath: `${consolePathPrefix}/SNES.png`,
    consoleOrigin: Console.SNES,
  },
  {
    trackName: "Rainbow Road (Wii)",
    song: "https://www.mariowiki.com/images/c/c1/Switch_Wii_Rainbow_Road_BCP.mp3?f3bc6",
    trackLayoutPath: `${cupPathPrefix}/Spiny/RainbowRoadWii/map.png`,
    cup: "Spiny Cup",
    screenshotPath: `${cupPathPrefix}/Spiny/RainbowRoadWii/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Spiny/RainbowRoadWii/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Spiny/SpinyCup.png`,
    consolePath: `${consolePathPrefix}/Wii.png`,
    consoleOrigin: Console.Wii,
  },
];
