import { Answer } from "./answer";
import { Console } from "./answer";

const cupPathPrefix = "/assets/Cups";
const consolePathPrefix = "/assets/ConsoleOrigins";

export const answerSet: Array<Answer> = [
  {
    trackName: "Mario Kart Stadium",
    song: "https://www.mariowiki.com/images/7/7a/MK8-Music-MarioKartStadium.oga?d1f20",
    trackLayoutPath: `${cupPathPrefix}/Mushroom/MarioKartStadium/map.png`,
    cup: "Mushroom Cup",
    screenshotPath: `${cupPathPrefix}/Mushroom/MarioKartStadium/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Mushroom/MarioKartStadium/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Mushroom/MushroomCup.png`,
    consoleOrigin: Console.WiiU,
    consolePath: `${consolePathPrefix}/WiiU.png`,
  },
  {
    trackName: "Water Park",
    song: "https://www.mariowiki.com/images/a/a1/MK8-Music-WaterPark.oga?b805f",
    trackLayoutPath: `${cupPathPrefix}/Mushroom/WaterPark/map.png`,
    cup: "Mushroom Cup",
    screenshotPath: `${cupPathPrefix}/Mushroom/WaterPark/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Mushroom/WaterPark/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Mushroom/MushroomCup.png`,
    consoleOrigin: Console.WiiU,
    consolePath: `${consolePathPrefix}/WiiU.png`,
  },
  {
    trackName: "Sweet Sweet Canyon",
    song: "https://www.mariowiki.com/images/7/79/MK8-Music-SweetSweetCanyon.oga?d3314",
    trackLayoutPath: `${cupPathPrefix}/Mushroom/SweetSweetCanyon/map.png`,
    cup: "Mushroom Cup",
    screenshotPath: `${cupPathPrefix}/Mushroom/SweetSweetCanyon/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Mushroom/SweetSweetCanyon/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Mushroom/MushroomCup.png`,
    consoleOrigin: Console.WiiU,
    consolePath: `${consolePathPrefix}/WiiU.png`,
  },
  {
    trackName: "Thwomp Ruins",
    song: "https://www.mariowiki.com/images/7/75/MK8-Music-ThwompRuins.oga?6c787",
    trackLayoutPath: `${cupPathPrefix}/Mushroom/ThwompRuins/map.png`,
    cup: "Mushroom Cup",
    screenshotPath: `${cupPathPrefix}/Mushroom/ThwompRuins/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Mushroom/ThwompRuins/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Mushroom/MushroomCup.png`,
    consoleOrigin: Console.WiiU,
    consolePath: `${consolePathPrefix}/WiiU.png`,
  },
  {
    trackName: "Mario Circuit",
    song: "https://www.mariowiki.com/images/0/09/MK8-Music-MarioCircuit.oga?2a3f4",
    trackLayoutPath: `${cupPathPrefix}/Flower/MarioCircuit/map.png`,
    cup: "Flower Cup",
    screenshotPath: `${cupPathPrefix}/Flower/MarioCircuit/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Flower/MarioCircuit/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Flower/FlowerCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Toad Harbor",
    song: "https://www.mariowiki.com/images/6/6b/MK8-Music-ToadHarbor.oga?7484d",
    trackLayoutPath: `${cupPathPrefix}/Flower/ToadHarbor/map.png`,
    cup: "Flower Cup",
    screenshotPath: `${cupPathPrefix}/Flower/ToadHarbor/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Flower/ToadHarbor/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Flower/FlowerCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Twisted Mansion",
    song: "https://www.mariowiki.com/images/6/6f/MK8-Music-TwistedMansion.oga?0e841",
    trackLayoutPath: `${cupPathPrefix}/Flower/TwistedMansion/map.png`,
    cup: "Flower Cup",
    screenshotPath: `${cupPathPrefix}/Flower/TwistedMansion/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Flower/TwistedMansion/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Flower/FlowerCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Shy Guy Falls",
    song: "https://www.mariowiki.com/images/6/63/MK8-Music-ShyGuyFalls.oga?4951c",
    trackLayoutPath: `${cupPathPrefix}/Flower/ShyGuyFalls/map.png`,
    cup: "Flower Cup",
    screenshotPath: `${cupPathPrefix}/Flower/ShyGuyFalls/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Flower/ShyGuyFalls/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Flower/FlowerCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Sunshine Airport",
    song: "https://www.mariowiki.com/images/4/4c/MK8-Music-SunshineAirport.oga?a6dbf",
    trackLayoutPath: `${cupPathPrefix}/Star/SunshineAirport/map.png`,
    cup: "Star Cup",
    screenshotPath: `${cupPathPrefix}/Star/SunshineAirport/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Star/SunshineAirport/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Star/StarCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Dolphin Shoals",
    song: "https://www.mariowiki.com/images/8/8c/MK8-Music-DolphinShoals.oga?2fcea",
    trackLayoutPath: `${cupPathPrefix}/Star/DolphinShoals/map.png`,
    cup: "Star Cup",
    screenshotPath: `${cupPathPrefix}/Star/DolphinShoals/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Star/DolphinShoals/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Star/StarCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Electrodrome",
    song: "https://www.mariowiki.com/images/1/1e/MK8-Music-Electrodrome.oga?a7de7",
    trackLayoutPath: `${cupPathPrefix}/Star/Electrodrome/map.png`,
    cup: "Star Cup",
    screenshotPath: `${cupPathPrefix}/Star/Electrodrome/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Star/Electrodrome/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Star/StarCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
  {
    trackName: "Mount Wario",
    song: "https://www.mariowiki.com/images/1/1c/MK8-Music-MountWario.oga?4e3c5",
    trackLayoutPath: `${cupPathPrefix}/Star/MountWario/map.png`,
    cup: "Star Cup",
    screenshotPath: `${cupPathPrefix}/Star/MountWario/screenshot.png`,
    trackMainImagePath: `${cupPathPrefix}/Star/MountWario/mainImage.png`,
    cupImagePath: `${cupPathPrefix}/Star/StarCup.png`,
    consolePath: `${consolePathPrefix}/WiiU.png`,
    consoleOrigin: Console.WiiU,
  },
];
