export const answerSet = new Set([
  "Mario Kart Stadium",
  "Water Park",
  "Sweet Sweet Canyon",
  "Thwomp Ruins",
  "Mario Circuit (Wii U)",
  "Toad Harbor",
  "Twisted Mansion",
  "Shy Guy Falls",
  "Sunshine Airport",
  "Dolphin Shoals",
  "Electrodrome",
  "Mount Wario",
  "Cloudtop Cruise",
  "Bone-Dry Dunes",
  "Bowser's Castle",
  "Rainbow Road (Wii U)",
  "Moo Moo Meadows",
  "Mario Circuit (GBA)",
  "Cheep Cheep Beach",
  "Toad's Turnpike",
  "Dry Dry Desert",
  "Donut Plains 3",
  "Royal Raceway",
  "DK Jungle",
  "Wario Stadium",
  "Sherbet Land",
  "Music Park",
  "Yoshi Valley",
  "Tick-Tock Clock",
  "Piranha Plant Slide",
  "Grumble Volcano",
  "Rainbow Road (N64)",
  "Yoshi Circuit",
  "Excitebike Arena",
  "Dragon Driftway",
  "Mute City",
  "Wario's Gold Mine",
  "Rainbow Road (SNES)",
  "Ice Ice Outpost",
  "Hyrule Circuit",
  "Baby Park",
  "Cheese Land",
  "Wild Woods",
  "Animal Crossing",
  "Neo Bowser City",
  "Ribbon Road",
  "Super Bell Subway",
  "Big Blue",
  "Paris Promenade",
  "Toad Circuit",
  "Choco Mountain",
  "Coconut Mall",
  "Tokyo Blur",
  "Shroom Ridge",
  "Sky Garden",
  "Ninja Hideaway",
  "New York Minute",
  "Mario Circuit 3",
  "Kalimari Desert",
  "Waluigi Pinball",
  "Sydney Sprint",
  "Snow Land",
  "Mushroom Gorge",
  "Sky-High Sundae",
  "London Loop",
  "Boo Lake",
  "Rock Rock Mountain",
  "Maple Treeway",
  "Berlin Byways",
  "Peach Gardens",
  "Merry Mountain",
  "Rainbow Road (3DS)",
  "Amsterdam Drift",
  "Riverside Park",
  "DK Summit",
  "Yoshi's Island",
  "Bangkok Rush",
  "Mario Circuit (DS)",
  "Waluigi Stadium",
  "Singapore Speedway",
  "Athens Dash",
  "Daisy Cruiser",
  "Moonview Highway",
  "Squeaky Clean Sprint",
  "Los Angeles Laps",
  "Sunset Wilds",
  "Koopa Cape",
  "Vancouver Velocity",
  "Rome Avanati",
  "DK Mountain",
  "Daisy Circuit",
  "Piranha Plant Cove",
  "Madrid Drive",
  "Rosalina's Ice World",
  "Bowser Castle 3",
  "Rainbow Road (Wii)",
]);
